### ISSUE TITLE
One-sided fisher test

### ISSUE THREAD

**Issue by fplazaonate** [juliangehring/HighSpeedStats#1]
Thank you very much for the HighSpeedStats package.
I would like to use the Fisher exact test with alternative="greater"
Is there an easy way to do so?
Thanks in advance.

**Comment by juliangehring** [comment]
You can use the `phyper` function in R base to get one-sided p-values of the FET with a very good perfomance. A nice explanation can be found in [Meng's blog post](https://mengnote.blogspot.co.uk/2012/12/calculate-correct-hypergeometric-p.html). One should note that `phyper` only works for one-sided p-values; this was one of the motivations for this package.
I'll try to add this information to the documentation of the package.

**Comment by juliangehring** [comment]
Closed with #2
